//define authro as we do in mongooese

import { UserIcon } from 'lucide-react';
import { defineField, defineType } from 'sanity';

export const playlist = defineType({
    name: "playlist",
    title: "Playlist",
    type: "document",
    icon: UserIcon,
    fields: [
        defineField({
            name: "title",
            type: 'string',
        }),
        // each author will have
        defineField({
            name: "slug",//isntaed of id we will have slug
            type: 'slug',
            options: {
                source: 'title',//slug will be generated from title
                //auto generated by sanity 
            }
        }),
       
        defineField({
            name: "select",
            type: 'array',
            of:[{type:'reference',to:[{type:"startup"}]}]
            //an array of diffrent refernces to a startup
            //means each title will refer to a muktiple array of startups
        }),
       
    ],
  //dont need a previwe?
})
