//define authro as we do in mongooese

import { UserIcon } from 'lucide-react';
import { defineField, defineType } from 'sanity';

export const startup = defineType({
    name: "startup",
    title: "Startup",
    type: "document",
    icon: UserIcon,
    fields: [
        defineField({
            name: "title",
            type: 'string',
        }),
        // each author will have
        defineField({
            name: "slug",//isntaed of id we will have slug
            type: 'slug',
            options: {
                source: 'title',//slug will be generated from title
                //auto generated by sanity 
            }
        }),
       
        defineField({
            name: "author",
            type: 'reference',
            to: { type: 'author' }
            //reference to a type author from author.ts
        }),
        defineField({
            name: "views",
            type: 'number',
        }),
        defineField({
            name: "description",
            type: 'text',
        }),
        defineField({
            name: "category",
            type: 'string',
            validation: (Rule) => Rule.min(1).max(20).required().error('please enter a category'),
            //adding validation to category
        }),
        defineField({
            name: "image",
            type: 'url',
            validation:(Rule)=>Rule.required(),
        }),
        defineField({
            name: "pitch",
            type: 'markdown',
            //custome field uses  officila markdown plugin from sanity
            //npm install sanity-plugin-markdown
            //configure it in sanity.config.ts in plugins section
            //in app/layout.tsx import the css for markdown editor
        }),
    ],
  //dont need a previwe?
})
